"""empty message

Revision ID: 3e8979af3dee
Revises: b48d52953588
Create Date: 2019-05-08 11:47:08.103876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8979af3dee'
down_revision = 'b48d52953588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wife',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wname', sa.String(length=30), nullable=True),
    sa.Column('wage', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tid'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wife')
    # ### end Alembic commands ###
