# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-14 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uname',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uphone',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机'),
        ),
    ]
